version: '3.8'

services:
  frontend:
    image: frontend:latest
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: backend:latest
    ports:
      - 8080:8080
    container_name: backend
